version: '3'
services:
    web:
        restart: always
        build:
            context: ./web
            args:
                - mix_env=prod
        environment:
            - MIX_ENV=prod
            - FB_EV_MAP_DEFAULT_TOKEN=${FB_EV_MAP_DEFAULT_TOKEN}
        links:
            - redis:redis
        ports:
            - "5050:5050"

    redis:
        restart: always
        build: ./redis
